name: Link-check
on:
  schedule:
    - cron: '0 1 * * *'  # 1 am everyday
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linksafe
        uses: TechWiz-3/linksafe@main
        with:
          whitelist_links: "http://masnun.com/2015/11/13/python-generators-coroutines-native-coroutines-and-async-await.html"
